### PR TITLE
Update Jenkins description update to use native client

### PR DESCRIPTION
**Pull request by terceiro**

### CODE REVIEW

**Comment by xando** [comment]
This change doesn't seem to work for me. 

I reverted the merge in 9a21f388a9da563273b4409801b5baa645418098 feel free to add it again.

**Comment by mwasilew** [comment]
Did you have your public key setup in jenkins?

**Comment by xando** [comment]
Yes. The problem for me was that this jar doesn't accept username anywhere.

**Comment by mwasilew** [comment]
I guess this is expected. As I talked to Antonio he reported authentication happens using SSH key without any username.

**Comment by xando** [comment]
I've tested it manually with 

```
java -jar /srv/art-reports.linaro.org/project/benchmarks/jenkins-cli.jar -s https://android-build.linaro.org/jenkins -i /srv/art-reports.linaro.org/ext/art-reports-bot.key set-build-description linaro-art-tip-build-nexus9-MicroBenchmarks-Baseline 463 "<a href="/#/build/382">Details</a><br/>"
```

```
Authentication failed. No private key accepted.
```

**Comment by mwasilew** [comment]
Which is also expected as I think Antonio tested with his key and I didn't update it later. Let me do that now.

**Comment by xando** [comment]
Merged it back, worked well

**Pull request merged**
