### PR TITLE
stats: support multiple charts on the stats page

### PR DESCRIPTION
**Pull request by terceiro**

### CODE REVIEW

**Comment by terceiro** [comment]
Just pushed a new version, and I now consider it ready

**Comment by mwasilew** [comment]
Looks good. I think one more item might be added - progress indicator when loading subsequent charts. After selecting a new metric to be plotted 'nothing happens' for a moment which might be a bit confusing to the user.

**Comment by terceiro** [comment]
that's true, I ended up forgetting to get back to that. Will do.

**Comment by terceiro** [comment]
Just improved that. Now the user has immediate feedback that something is going on

**Comment by mwasilew** [comment]
I found the bug. The list of charts 'freezes'. Steps:

1. open stats page
2. add some next metric (for example NSieve)
3. try to choose same metric again (for example NSieve)
4. try to add next metric (DeltaBlue)

Outcome:
 - new metric (DeltaBlue) doesn't show up in the list, shows up in the page though.

**Comment by terceiro** [comment]
Fixed!

**Comment by mwasilew** [comment]
Merging this PR. The JS bug will be addresed separately. The bug #86 is reported to track it.

**Pull request merged**
