### PR TITLE
add support for extracting compilation statistics

### PR DESCRIPTION
**Pull request by terceiro**
After this is applied, one has to run the following in production:

./manage.py recreate_result_data

### CODE REVIEW

**Comment by terceiro** [comment]
this replaces #95

after this is is applied, all result data needs to be recreated in order to
have the overall summary calculated correctly (i.e. recreating only the result
data corresponding to compilation statistics won't work).

**Comment by mwasilew** [comment]
OK, so this is why the chart turned unusable after adding only compilation statistics. Looks OK to me. Did you possibly try it on the production DB?

**Comment by terceiro** [comment]
I did on the local dump from some weeks back I had locally, and there was no noticeable change in the overall summary.

 I don't think there will be any issues, but we can try running on staging first just to be sure.

**Comment by terceiro** [comment]
I did on the local dump from some weeks back I had locally, and there was no noticeable change in the overall summary.

 I don't think there will be any issues, but we can try running on staging first just to be sure.

**Comment by mwasilew** [comment]
OK, let's merge it. Is there a chance you can roll it out to staging and production?

**Pull request merged**
