### PR TITLE
mail: include links to download data files

### PR DESCRIPTION
**Pull request by terceiro**

### CODE REVIEW

**Comment by terceiro** [comment]
as usual, reviewing commit by commit will be a lot easier since this PR touches
quite a few places.

**Comment by mwasilew** [comment]
I pulled the change locally and it seems not to work when the test job name contains ".". Did you try with production data? We have the test jobs with id "J16_linaro-art-stable-m-build-MicroBenchmarks_bullhead_64_a53_aot.json". The TestJob.id gets stripped by regex to "J16_linaro-art-stable-m-build-MicroBenchmarks_bullhead_64_a53_aot". Than I'm getting 500 as this ID doesn't exist in db. The actual URL that is generated in the page is: /api/testjobdata/J16_linaro-art-stable-m-build-MicroBenchmarks_bullhead_64_a53_aot.json.json

**Comment by terceiro** [comment]
> I pulled the change locally and it seems not to work when the test job
> name contains ".".

argh. yeah I kind of assumed there will be no "." in ids, but of course
that is wrong. I'll fix that

**Comment by terceiro** [comment]
there; just pushed an updated set of commits that DTRT

**Comment by mwasilew** [comment]
Works for me.

**Pull request merged**
